
Vagrant.configure("2") do |config|

  # https://docs.vagrantup.com.

 
  config.vm.box = "ubuntu-22.04"
  #config.vm.provider = "hyperv"
  #config.vm.network = "PhysicalLan"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end

  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
  end

  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"
  end
end
