# https://github.com/apache/nifi/tree/main/nifi-docker/dockerhub
# Accessible through ssh tunneling (e.g. ssh -L localhost:8443:<clusterip>:8443 <nodeip>)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      demo: nifi
  replicas: 1
  template:
    metadata:
      labels:
        demo: nifi
    spec: 
      containers:
      - name: nifi
        image: apache/nifi:latest
        ports: # https://github.com/apache/nifi/tree/main/nifi-docker/dockerhub#configuration-information
        - name: ui
          containerPort: 8443
        env:
        - name: SINGLE_USER_CREDENTIALS_USERNAME
          valueFrom:
            secretKeyRef:
              name: nifiuser
              key: username
        - name: SINGLE_USER_CREDENTIALS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nifiuser
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: nifi
spec:
  selector:
    demo: nifi
  ports:
  - port: 8443
    targetPort: ui
      