# Setup cilium
- name: add helm repo for cilium
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
    
- name: helm install cilium
  kubernetes.core.helm:
    name: cilium
    namespace: kube-system
    chart_ref: cilium/cilium
    chart_version: 1.15.3
    values: "{{ lookup('file', '../../inventory/cilium-vars.yaml') | from_yaml }}"