- name: Load required variables
  hosts: kubernetes
  tasks:
  - set_fact:
      purge_var: "{{ (purge | mandatory) in ['YES','yes','TRUE','true'] }}"
  - debug:
      msg: "Purge is {{ 'enabled' if purge_var else 'disabled' }}"

- name: Reset kubernetes
  hosts: kubernetes
  become: yes
  vars_prompt:
  - name: prompt
    prompt: |
      Type "NUKE" if you want to reset kubernetes (and delete all images and containers) on the following hosts:
    
      {{ ansible_play_batch }}
    
      Any other input will end the play.
    private: false
  roles: 
  - role: k8s-reset
    purge: "{{purge_var | bool}}"