- debug:
    msg: "{{ inventory_hostname }}: architecure {{ansible_facts['architecture']}} is not supported"
  when: arch == "Unsupported"
- meta: end_host
  when: arch == "Unsupported"

- debug: 
    msg: "{{ ansible_facts['distribution'] }} is not supported"
  when: ansible_facts['distribution'] != "Ubuntu"
- meta: end_host
  when: ansible_facts['distribution'] != "Ubuntu"

- include_tasks: cli.yaml

- include_tasks: hubble.yaml

- copy:
    content: "{{ cilium_config_contents }}"
    dest: ~/cilium-vars.yaml

- name: Installing cilium
  command: cilium install -f ~/cilium-vars.yaml