- name: Replace cilium
  hosts: all
  tasks:

  - name: copy cilium variables
    become: yes
    copy:
      src: ../../inventory/cilium-vars.yaml
      dest: /root/cilium.yaml
      owner: root
      group: root
      mode: 0400
    when: 
    - hostvars[inventory_hostname].k8s.type == "bootstrap"

  # TODO: look at upgrade, might have side effects, so uninstall, install for now
  - name: uninstall cilium
    command: cilium uninstall
    when: 
    - hostvars[inventory_hostname].k8s.type == "bootstrap"

  - name: install cilium
    become: yes
    command: cilium install --values /root/cilium.yaml
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf 
    when: 
    - hostvars[inventory_hostname].k8s.type == "bootstrap"