# kubadm reset
# TODO: maybe add deepclean extra-var to apply nerdctl system prune and crictl rm/rmi

- name: Resetting cluster nodes
  hosts: all
  become: yes
  tasks:
  - name: reset kubeadm
    command: kubeadm reset --force

  - name: remove cni net.d
    file: 
      path: /etc/cni/net.d
      state: absent

  - name: reset iptables
    command: iptables -F

  - name: remove haproxy
    apt:
      pkg:
      - haproxy
      state: absent
      purge: yes
      autoremove: yes
    when:
    - hostvars[inventory_hostname].loadbalancer is defined

  - name: remove haproxy config
    file: 
      path: /etc/haproxy
      state: absent
    when:
    - hostvars[inventory_hostname].loadbalancer is defined

  - name: reboot
    reboot: