# Add a worker to the cluster
# TODO: review loading of hash and token

- name: load kubernetes variables
  include_vars:
    file: ../../inventory/k8s-vars.yaml
    name: kubernetes

- name: privileged block
  become: yes
  block:
  - name: Check if node already joined
    stat: path=/etc/kubernetes/pki/ca.crt
    register: joined
  
  - name: Copy JoinConfiguration
    vars:
      token: "{{ lookup('file', '../../secrets/token-{{ inventory_hostname }}' ) | trim }}"
      hash: "{{ lookup('file', '../../secrets/hash') | trim }}"
    template:
      src: ../configs/join.j2
      dest: /root/join.yaml
      owner: root
      group: root
      mode: 0400
    when: not joined.stat.exists

  # TODO: delete local token

  - name: Join cluster
    command: kubeadm join --config=/root/join.yaml
    when: not joined.stat.exists

  - debug: msg="Node already contains kubelet config. Consider draining the node and running kubeadm reset"
    when: joined.stat.exists