- name: Setting up hosts
  hosts: all
  become: yes
  tasks:
  - name: Install hyperv modules
    include_tasks: hyperv-vm.yaml

  - name: Copy network files
    include_tasks: normalize-networking.yaml

  - name: Remove unused packages
    include_tasks: remove-ubuntu2310.yaml
    when: hostvars[inventory_hostname].os == "ubuntu2310-fresh"
  
  - name: Update packages
    apt: 
      update_cache: yes
      upgrade: dist

  - name: Prepare for k8s
    include_tasks: prepare-k8s.yaml
  
  - name: Reboot to apply changes (networking & containerd)
    reboot: